apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - name: student
          image: 20i0964/scd_lab_final:student
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/lab_final
---
apiVersion: v1
kind: Service
metadata:
  name: student
spec:
  selector:
    app: student
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5003
  type: ClusterIP
