apiVersion: apps/v1
kind: Deployment
metadata:
  name: examination
spec:
  replicas: 2
  selector:
    matchLabels:
      app: examination
  template:
    metadata:
      labels:
        app: examination
    spec:
      containers:
        - name: examination
          image: 20i0964/scd_lab_final:examination
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/lab_final
---
apiVersion: v1
kind: Service
metadata:
  name: examination
spec:
  selector:
    app: examination
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
