apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faculty
  template:
    metadata:
      labels:
        app: faculty
    spec:
      containers:
        - name: faculty
          image: 20i0964/scd_lab_final:faculty
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/lab_final
---
apiVersion: v1
kind: Service
metadata:
  name: faculty
spec:
  selector:
    app: faculty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
