apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
        - name: attendance
          image: 20i0964/scd_lab_final:attendance
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/lab_final
---
apiVersion: v1
kind: Service
metadata:
  name: attendance
spec:
  selector:
    app: attendance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
